### PR TITLE
Appbar Input cues

### PR DESCRIPTION
**Pull request by Gskartwii**
Found this branch while purging out stale branches, might be worth a revisit.

### CODE REVIEW

**Comment by eLunate** [comment]
Do all of the modules for it load happily with these commits?

**Comment by Gskartwii** [comment]
I wish I knew. It's been so long since I worked on this.

**Comment by eLunate** [comment]
Test later >.>

**Comment by Gskartwii** [comment]
I would actually like a dedicated tester to test it, especially since it's going to solve #2 which is an old issue with the overlay-stable milestone.

**Comment by Gskartwii** [comment]
I'll actually close this, it's not relevant anymore with the new design.

**Pull request closed without merging**
